url: http://www.voyageofthesongbird.com
baseurl: /

# Site settings
title: Voyage of the Songbird
email: your-email@domain.com
description: "We’re looking for sponsors to help the crew hoist sail – either through gear or content backing.  Any gear donated will result in images of the team using said item on the trip as well as any agreed upon branded content to be used by the companies participating."


# Team names, titles and social links
people:
- name: Jerome Francois Crandall Hollick
  pic: 1
  position: Captain
  bio: of the Songbird has had a lifelong dream to sail to the Caribbean in the open Atlantic. With over 38,000 hours at the helm running New York’s charter <a href="http://www.tivolisailing.com">Tivoli Sailing Company</a> and teaching thousands of young aspiring sailors across the Hudson Valley, he’s assembled a formidable crew for the big show.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Brian K. Vandeyar
  pic: 2
  position: First Mate
  bio: has spent years on deck with Captain Jerome. Brian is an independent Master Carpenter, having personally hand-built many of the Hudson Valley’s most high-end residential estates. 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Dan Stone
  pic: 3
  position: Navigator & Electronics Expert
  bio: is the tech specialist behind the journey, as Principal and Senior Creative Technologist of <a href="http://www.evolvingmedia.net">Evolving Media Network</a>, Co-Founder of <a href="http://www.catskillsconf.com">Catskills Conf</a> and <a href="http://meetup.com/hvtech">Hudson Valley Tech Meetup</a>.
  social:
    - title: twitter
      url: http://www.twitter.com/dafstone
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Jenna Matecki
  pic: 4
  position: Cultural Attaché & Onboard Reporter
  bio: is the communications lead at sea. As Founder & CEO of story development company <a href="http://matekico.com">Matecki & Co.</a>, <a href="http://jennamatecki.com">Jenna</a> is a content strategist and communications consultant. She’s also the host of the weekly podcast <a href="http://notesondoing.com">Notes on Doing</a>.
  social:
    - title: twitter
      url: http://www.twitter.com/dafstone
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
